set -g mouse on

# Start windows and panes at 1, not 0
set  -g base-index      1
setw -g pane-base-index 1

# Use Ctrl+a as the prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix


# Keep working directory for new panes/windows
bind '"' split-window -v -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"
bind 'c' new-window -c "#{pane_current_path}"

# Use vim navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

